[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-Ctarget-cpu=cortex-m7",
    "-Clink-arg=-Tt4link.x",
    "-Clink-arg=-Tdefmt.x",
    "-Clinker-plugin-lto"
]
